name: continuous validation

on:
  push:
  schedule:
    - cron: '10 1 * * *'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate
        run: |
          pushd grammar
            ./validate.sh
          popd